### ISSUE TITLE
Extract metadata for mobi and AZW3?

### ISSUE THREAD

**Issue by vanabel** [kevinhendricks/KindleUnpack#12]
Is it possible to extract metadata from mobi/azw3(non protected) files? It would be greate to return these metadata (author/title/category) as an array.

**Comment by kevinhendricks** [comment]
Any normal azw3/mobi even with drm has an unencrypted exth header where all the metadata is stored.  See the DumpMobiHeader program for a python tool that will dump the metadata and the complete header as a text file you could collect and post process or modify the code yourself.

**Comment by vanabel** [comment]
Thanks, very useful. But could you please help me again to show an example of how to get the title by `php`: I try to use
```
$fp = fopen('test.mobi', 'r');
echo fgets($fp,503);
```
it seems not work. I think there must be some end positon need be set. But how?

**Comment by kevinhendricks** [comment]
Sorry but It  is not simple.  Please get the DumpMobiHeader python program from here and try to replicate what it does to find and read the exth section from each header record.  Or alternatively, modify that python program to only dump the metadata and then use php to parse its text output.
