### ISSUE TITLE
unpack awz4 is grayed out

### ISSUE THREAD

**Issue by misbell** [kevinhendricks/KindleUnpack#20]
so, it doesn't do anything. I installed apprentice alf's latest also. 

NOTE: on calibre on my old MacBook Pro, awz4 is unpacked without any problem. But it's now working with new install on my new MacBook Pro. That's why I installed KindleUnpack.

**Comment by dougmassay** [comment]
Sounds like you might be talking about the calibre plugin. This is the standalone program that plugin is based on.

**Comment by kevinhendricks** [comment]
Clsing as this is I believe a calbre plugin kindleunpack issue.  Please discuss this issue in the correct Forum on www.mobileread.com
