### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by znbook** [kevinhendricks/KindleUnpack#21]
```
KindleUnpack v0.80
Traceback (most recent call last):
  File "kindleunpack.py", line 1020, in <module>
    sys.exit(main())
  File "kindleunpack.py", line 953, in main
    print("   Based on initial mobipocket version Copyright 漏 2009 Charles M. Hannum <root@ihack.net>")
UnicodeEncodeError: 'gbk' codec can't encode character u'\xa9' in position 49: illegal multibyte sequence
```

while when I switch to python 3.4, and other error occured.
```
Traceback (most recent call last):
  File "K:/Program/Development/pyDev/online/KindleUnpack/lib/kindleunpack.py", line 183, in <module>
    from .unpack_structure import fileNames
  File "K:/Program/Development/pyDev/online/KindleUnpack/lib\unpack_structure.py", line 163
    nzinfo.external_attr = 0o600 << 16L # make this a normal file
                                      ^
SyntaxError: invalid syntax
```

by the way, how can I convert the whole project to .exe? I've tried py2exe and pyinstaller, but both of them could not convert it correctly...
the following  code didn't work for me...
`pyinstaller -p lib -F lib\kindleunpack.py --hidden-import compatibility_utils --hidden-import unipath  --hidden-import unpack_structure  --hidden-import mobi_utils `

when execute kindleunpack.exe, error occured....
```
ImportError: No module named mobi_utils
[9208] Failed to execute script kindleunpack
```

**Comment by dougmassay** [comment]
Yeah, that's from the latest Pull Request. The L in the bitwise operation is not valid in Python 3. Must've only tested with Python2.

The following seems to work the same in both Python2.7+ and 3.X+, though:

`nzinfo.external_attr` = 0o600 << 16

Might have to do something different if we want to support pythons older than 2.7, though.

As far as the encoding error when using python2 goes ... that's the copyright symbol in KU's usage printout. We've had that cause problems before. I'm all for not attempting to print that character if it's going to cause hiccups like this. The old-fashioned (c) is good enough in my book.

**Comment by dougmassay** [comment]
I pushed a fix that will allow the program to launch with Python3: bbb696719aeeb7f651d343b2ee6775d58514e176

**Comment by znbook** [comment]
great work! I think I should learn more about how the different between py3 and py2.
by switch to py3, now it can ignore the encoding error and run correctly!

but though, I wonder know how to covert this project to executeable file(.exe)? this will be more easy to use.
Thanks again.

**Comment by dougmassay** [comment]
I don't really know, to tell the truth. I've never really worked much with the various "freeze" tools. I know we jump through a lot of hoops to make sure the scripts work with Python 2 and Python 3, so it doesn't surprise me that those freeze tools may have difficulty with KindleUnpack. We prefer to distribute it in non-binary form (for obvious reason), so we've never bothered to optimize it for use with py2exe or cx_freeze, or the like. You're basically on your own if you want to make an exe out of it.
