### ISSUE TITLE
Unable to unpack azw file with .opf content

### ISSUE THREAD

**Issue by iKoznov** [kevinhendricks/KindleUnpack#25]
Hello!
I'm running:
`py -3 lib/kindleunpack.py -r "Learning XML_ Creating Self-Describing Data_nodrm.azw" output_dir`
but it just fails:
```
KindleUnpack v0.82
   Based on initial mobipocket version Copyright © 2009 Charles M. Hannum <root@ihack.net>
   Extensive Extensions and Improvements Copyright © 2009-2014
       by:  P. Durrant, K. Hendricks, S. Siebert, fandrieu, DiapDealer, nickredding, tkeo.
   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, version 3.
Unpacking Book...
Traceback (most recent call last):
  File "lib/kindleunpack.py", line 1020, in <module>
    sys.exit(main())
  File "lib/kindleunpack.py", line 1008, in main
    unpackBook(infile, outdir, apnxfile, epubver, use_hd)
  File "lib/kindleunpack.py", line 873, in unpackBook
    raise unpackException('Invalid file format')
__main__.unpackException: Invalid file format
```
here is [this file](https://www.dropbox.com/s/074g5tsxon2unfn/Learning%20XML_%20Creating%20Self-Describing%20Data_nodrm.azw?dl=0).
I don't know how it was packed, but i think contents in [OEB format](https://en.wikipedia.org/wiki/Open_eBook). Inside i found mention of *.opf file.
![opf](https://user-images.githubusercontent.com/4540380/54084984-63f22d00-4349-11e9-8e78-e87cedf92d19.PNG)

**Comment by dougmassay** [comment]
That doesn't look like any kindlebook format I've seen. If it's indeed a valid kindlebook then it's probably in the newer KFX format that KindleUnpack doesn't handle.

**Comment by pdurrant** [comment]
I think the file's got mangled. the CONT first four character make me think it might be the back end of a ebook file, not the whole thing.

Just re-download and strip the DRM again.

**Comment by kevinhendricks** [comment]
FWIW:  I just tried loading it as is into calibre and it says it is in KFX format and warns there are missing pieces.

**Comment by iKoznov** [comment]
Kindle for Windows opens it fine. I removed drm already.

**Comment by dougmassay** [comment]
Regardless of whether or not newer versions of Kindle for Windows might be able to open DeDRMed ebooks in the KFX format, KindleUnpack definitely cannot. The bottom line is that you cannot unpack KFX kindlebooks with KindeUnpack at this time.
