### ISSUE TITLE
Have considered package kindle ebooks parser into a pip package?

### ISSUE THREAD

**Issue by stardiviner** [kevinhendricks/KindleUnpack#33]
I searched PyPi library, `pip search kindle` and `pip search mobi`. But no lucky.

Then I found this project. I'm thinking, can this project separate out the kindle ebook formats parser out? So many people can benefit from it.

WDYT?

**Comment by kevinhendricks** [comment]
This project was jointly authored by epub creators and others at the www.mobileread.com forum site.  It tries its best to recreate the epub that was passed to kindlegen.  It can not always succeed so followup work with a epub editor like Sigil or Calibre is often needed.
 It can not handle DRM kindle ebooks, nor can it handle the very latest Kindle ebooks format.

This project is not of interest to the general python community and instead is meant for the community of ebook developers at Mobileread where it evolved and started.  We have no plans to make it a "package".

**Comment by stardiviner** [comment]
I see, thanks for replying.

**Comment by dougmassay** [comment]
For the record, it's not particularly difficult for an end user to install kindleunpack as a python package. All you need is a setup.py file that will do what needs to be done. The latest version of kindleunpack is maintained in the Arch Linux User Repository. He makes a tiny patch to an existing file and creates the setup.py file to allow installing as a package with `python setup.py install`.

The patch file that creates the setup.py file [can be found here](https://aur.archlinux.org/cgit/aur.git/tree/Installing-with-setuptools.diff?h=kindleunpack).

The two exposed entry points are kindleunpack-cli and kindleunpack-gui

Note that on Linux, the setup.py file copies the .pyw file to .py (pyw is meaningless on linux and .pyw files cannot be imported from).

**Comment by stardiviner** [comment]
Thanks a lot @dougmassay . I will take a try on my computer.

**Comment by clach04** [comment]
Summary:

* archlinux has a package https://aur.archlinux.org/packages/kindleunpack as per https://github.com/kevinhendricks/KindleUnpack/issues/33#issuecomment-638323193
* https://github.com/iscc/mobi has a Python 3.7+ package available from PyPI available from https://pypi.org/project/mobi/ and via pip
* https://github.com/clach04/KindleUnpack quick and dirty hack which is importable, optionally pip installable (but not from PyPI)
