### ISSUE TITLE
KindleUnpack_ReadMe.htm references incorrect Python version

### ISSUE THREAD

**Issue by WEricBr** [kevinhendricks/KindleUnpack#37]
The KindleUnpack_ReadMe.htm file has the following as the Python requirement:
        _The KindleUnpack program requires Python 2.6 or 2.7 to function properly._

Where the README.md has the following as the Python requirement:
        _The KindleUnpack program requires Python 2.7.X or Python 3.4 or later to function properly._

**Comment by kevinhendricks** [comment]
Thanks for the head's up.  I will update the .htm version.

**Comment by kevinhendricks** [comment]
fixed in master
