### ISSUE TITLE
Convert `original-resolution` to `rendition:viewport`

### ISSUE THREAD

**Issue by johnfactotum** [kevinhendricks/KindleUnpack#39]
Some fixed-layout KF8 books don't have the `viewport` `meta` tag within each page and, while there is viewport data in the file ("original-resolution" in EXTH), KindleUnpack only outputs
```xhtml
<meta name="original-resolution" content="1072x1448" />
```
It would be better if it could convert it into the [rendition:viewport](https://www.w3.org/publishing/epub32/epub-packages.html#viewport) property:
```xhtml
<meta property="rendition:viewport">width=1072, height=1448</meta>
```
Indeed, it looks like it used to do that, but for it was commented out for some reason: https://github.com/kevinhendricks/KindleUnpack/blob/c8be31a196fd92803f78ad34a3f18d40319bbac5/lib/mobi_opf.py#L675-L686

For more context, as well as link to an example file, see https://github.com/johnfactotum/foliate/issues/940

**Comment by kevinhendricks** [comment]
Code would need to be added to add that property to every single xhtml page in its head element and  not just to the opf metadata.  This can be easily done with Sigil or Calibre using regex find and replace.

Neither Sigil nor Calibre support editing or viewing fixed layout epubs.  Furthermore, I have no fixed layout kf8s nor fixed layout epubs in my personal collection to test with.  I would need both in order to test things with.

All that said ...  well thought out and tested Pull Requests are welcome.

**Comment by kevinhendricks** [comment]
I missed your comment about the sample file in your link.  I will grab it to take a look.  But that said, because neither Calibre nor Sigil support fixed layout epubs, this is not a high priority for KindleUnpack as a real solution would require  adding something to each previously generated page (if added during the original generation phase it would break encoded page/link offsets) so it can only be done in a new post processing stage.

**Comment by kevinhendricks** [comment]
I checked the epub3 fixed layout spec:

https://idpf.org/epub/fxl/#dimensions

It seems for each individual xhtml page, inside its head element the following simple meta data must be add is the epub is pre-paginated:

<meta name="viewport" content="width=1200, height=610"/>

obviously for the actual specified height and width.

A fixed layout epub3 OPF does *not* actually specify the dimensions in its metadata, unlike the exth in a Kindle fixed layout.  It leaves it for individual xhtml pages to specify.

So leaving the original-resolution in the opf metadata as an epub2 like meta element that will be ignored under epub3 seems like the right approach, but each individual xhtml page would still need to be "fixed" with the addition of the above.

**Comment by kevinhendricks** [comment]
To make matters even worse, under epub3 you can even mix reflowable with fixed layout in the same epub by xhtml page by adding the "rendition:layout-pre-paginated" to that spine's itemref properties list for just the xhtml pages that have fixed versus reflowable formats.

See "Example 3" in the epub fixed layout spec link I posted above.

Needless to say, full support for such fixed-layout epubs in KindleUnpack will not for forthcoming.  PDF is simple a better fixed layout format when fixed layout is important.

**Comment by johnfactotum** [comment]
It's probably not necessary to add that property to every page because (IMO) it's not really the job of KindleUnpack to unsure that the output is valid, only that the output should be as close as the source EPUB as possible.

`rendition:viewport` is deprecated, and technically I think the [(old, EPUB 3.0.1) spec](https://idpf.org/epub/301/spec/epub-publications.html#fxl-property-viewport) says that if present, they must match the size provided in the `viewport` `meta` tag. To quote from the spec, "the property serves as a complement to facilitate Reading System optimization of the rendering". Whatever "complement" means.

The most sensible behavior for any reading system would be to use `rendition:viewport` as a fallback when the pages doesn't have the meta tag. And even if no reading system actually does that, at least it's still a standard property, unlike `original-resolution`.

**Comment by kevinhendricks** [comment]
The epub3 spec calls for it on every xhtml page, so I would guess Amazon's kindle create/kindle preview is stripping it out in KF8s and generating the exth key in the opf.

According to that epub3 spec, there is no "rendition:viewport" metadata element in the epub3 OPF,  just in the XHTML Meta as I stated above so creating one in the epub3 OPF just makes no sense as it is not spec.  So leaving it in as info only "original-resolution" seems like the nicest spec compliant thing to do.

Adding its info  to each XHTML page (as was mentioned in the original KindleUpack To-Do comment code) is what I am willing to take a look at.

Adding in a *non-spec* "rendition:viewport" metadata element to the OPF is not something we will be doing.

**Comment by johnfactotum** [comment]
> According to that epub3 spec, there is no "rendition:viewport" metadata element in the epub3 OPF

Yes, there is: https://www.w3.org/publishing/epub32/epub-packages.html#viewport. It's just deprecated.

**Comment by kevinhendricks** [comment]
Okay, I see it now in the epub-3.0.1 spec but as you said it is long deprecated.
It  clearly states this mechanism does not replace the need to use the viewport meta in the head element of every single xhtml page.

So I am still not sure if it is worth the effort for KindleUnpack to deal with this at all given neither Calibre nor Sigil support fixed layout epubs.

**Comment by kevinhendricks** [comment]
Okay, I took a look at the XHTML K8 code and I think I can see a straightforward way to pass along a viewport meta item to each part and properly inject it into each xhtml page.  Then by simply uncommenting the "to-do" code in mobi-opf we can insert the deprecated meta property.

That said, KindleUnpack will not be supporting any epubs that mix the fixed layout and reflowable layouts in the same epub.  It will assume if it finds original-resolution in the exth it will extract the size and apply it to ALL xhtml pages since true fixed format epubs are quite rare outside of children's books.

Would that help?

**Comment by johnfactotum** [comment]
> It will assume if it finds original-resolution in the exth it will extract the size and apply it to ALL xhtml pages

It's probably fine, as reading systems will (or they should) check the spine overrides (the `properties` attribute on `<itemref>`s). I believe this info is only available in the RESC record (if it has one)? Otherwise, it won't be possible to support mixed layout books, anyway. But if it has those properties, then KindleUnpack can check them before injecting the tag.

**Comment by kevinhendricks** [comment]
Given parsing the leftover opf pieces stuck in a mobi section is fraught with issues, I will ignore it.  

Furthermore, based on testing from admittedly long ago, the kindle produced mobi was either all fixed or all reflowable not mixed.  Of course I have never seen a mixed reflowable / fixed epub3 in the wild even either.

**Comment by kevinhendricks** [comment]
I made the proposed changes in the local tree and tested them with the linked demo but the output really makes no sense (at least to me).

Here is a snippet of the new output of the OPF:

```
    <meta content="1072x1448" name="original-resolution"/>
    <meta property="rendition:layout">pre-paginated</meta>
    <meta property="rendition:orientation">portrait</meta>
    <meta property="rendition:viewport">width=1072, height=1448</meta>
```

Here is a snippet from one of the parts:

```
<!DOCTYPE html SYSTEM "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head>
<title>第89页</title>
<link rel="stylesheet" type="text/css" href="../Styles/style0001.css"/>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta name="viewport" content="width=1072, height=1448"/>
</head><body>
<div class="fs">
	<div>
		<img src="../Images/image00098.jpeg" alt="Comic Book Images" class="singlePage" width="1024" height="1536"/>
	</div>
</div>
</body></html>
```

Notice the image width and height are strange given the original resolution value.

Using an image height = 1536 when the viewport height is 1448 seems a bit strange.  There is no text so no real need to even use a fixed format layout and nothing is being positioned as far as I can tell.  It is just a set of images.

I tried with both the EpubJS Sigil plugin and the Readium Sigil Plugin 
(see https://www.mobileread.com/forums/showthread.php?t=247431) but I can not tell if what either of them are showing changes or are more correct than the version created by current KindleUnpack without these modifications.

If the Readium reader does not play well with this, I am not sure what will.

So are these changes even worth committing to master?

**Comment by johnfactotum** [comment]
> Using an image height = 1536 when the viewport height is 1448 seems a bit strange.

Yes, a bit strange. It looks like it's overridden with CSS with `height: 100%;` and `width: auto;`, and one of the parent `<div>`s has `height: 1448px;` and `width: 1072px;`. So it appears that 1072x1448 is indeed the correct size. The intention seems to be to add some margins to the sides, as the aspect ratio of 1072x1448 is slightly wider than 1024x1536.

> There is no text so no real need to even use a fixed format layout and nothing is being positioned as far as I can tell. It is just a set of images.

I believe this is typical for comic books.

> If the Readium reader does not play well with this, I am not sure what will.
>
> So are these changes even worth committing to master?

I think you're right, it seems there's something wrong with the rendering of this book apart from getting the correct viewport size. FWIW Readium appears to support `rendition:viewport` (see https://github.com/readium/readium-js/commit/6411402bf0e31463ccf408dc0e8ccc487c16a169 and the linked issues). Unlike, Epub.js, which apparently has *some* code reading that property but I don't think it's actually doing anything with it.

But if the size is not available in either the .opf or the .xhtml, then there's no way for the reading system to get the correct size at all. At best they can try to use the width and height of the image on the page (if there is one) as a fallback (which, looking at its code, seems to be what Readium does), which in this case would be less correct, as the containing `<div>` does set a different size from the image.

**Comment by kevinhendricks** [comment]
From that perspective you are right ... the size needs to be available someplace or nothing has a chance to work.  

And with the opf version being deprecated, having it in both the .opf and .xhtml seems to be important for future proofing things even if no reader seems to work with it right now.

I still have to test these changes a bit more to make sure they do not break anything under older python 2.x just to be safe. 

 If you know of any other mobi fixed format test files that are not just a stream of images for testing purposes, I would appreciate a link.

Once tested, I will push these changes to master.

**Comment by johnfactotum** [comment]
> If you know of any other mobi fixed format test files that are not just a stream of images for testing purposes, I would appreciate a link.

I came across this one some while ago: https://book4you.org/book/5691417/a66983. It does have the `viewport` `meta` tag on each page, though the pages will spread correctly if you lay them starting from the left (and there are no `page-spread-*` properties in RESC, either).

**Comment by johnfactotum** [comment]
Another sample file from BB eBooks: https://bbebooksthailand.com/phpscripts/bbdownload.php?ebookdownload=RealMotherGoose-FXLMOBI.

**Comment by kevinhendricks** [comment]
Thank you.  I will test with both.

**Comment by kevinhendricks** [comment]
It seems that kindlegen is not stripping out the viewport meta from each xhtml as shown by your first new sample but it is missing in the original problem mobi and missing in the MotherGoose fixed layout mobi.

So I search for that viewport meta before injecting anything into each part.

I have pushed these changes to master.

https://github.com/kevinhendricks/KindleUnpack/commit/de9a9cf79b7ab53879647c6b419493cf69345f0d


These changes only impact 3 files:  kindleunpack.py mobi_opf.py and mobi_html.py.

Please give them a try to see if they do what you want.  If so, let me know and  they will go into the next official release.

**Comment by johnfactotum** [comment]
Seems to be working great. Thanks!

**Comment by kevinhendricks** [comment]
Good to know.  Not sure when the next official release will be, so feel free to use master until enough smaller changes build up to warrant a full release.

Closing this as now fixed in master.
