### ISSUE TITLE
encoding issue with source code under Microsoft Windows and default codepage

### ISSUE THREAD

**Issue by clach04** [kevinhendricks/KindleUnpack#41]
Error when running under Python 2.7 under windows with command line to get usage/help output:

    C:\code\py\KindleUnpack>py -2 lib\kindleunpack.py
    KindleUnpack v0.83
    Traceback (most recent call last):
      File "lib\kindleunpack.py", line 1029, in <module>
        sys.exit(main())
      File "lib\kindleunpack.py", line 964, in main
        print("   Based on initial mobipocket version Copyright -¬ 2009 Charles M. Hannum <root@ihack.net>")
      File "C:\python2764\lib\codecs.py", line 369, in write
        data, consumed = self.encode(object, self.errors)
      File "C:\python2764\lib\encodings\cp437.py", line 12, in encode
        return codecs.charmap_encode(input,errors,encoding_map)
    UnicodeEncodeError: 'charmap' codec can't encode character u'\xa9' in position 49: character maps to <undefined>

Luckily not an issue under Python 3 :-)

I can think of two options to resolve:

1) remove non-ascii characters - e.g. common convention is to use `(c)` as alternative
2) document in the readme that the default code page of 437 cannot/should-not be used. E.g. something like:

--------------------
If you would prefer a command-line interface, simply look inside KindleUnpack's "lib" folder for the KindleUnpack.py python program and its support modules. You should then be able to run KindleUnpack.py by the following command:

    python kindleunpack.py [-r -s -d -h -i] [-p APNX_FILE] INPUT_FILE OUTPUT_FOLDER

NOTE Under Microsoft Windows, first issue:

    chcp 1252
--------------------

Any preferences? I'm happy to post a PR.

**Comment by kevinhendricks** [comment]
Known long standing issue.  Changes to support python2 on Windows with non-utf8 codepages will not be made and python2 is broken on Windows and end of life.  Use python3.
