### ISSUE TITLE
Book title not escaped in NCX

### ISSUE THREAD

**Issue by johnfactotum** [kevinhendricks/KindleUnpack#42]
The generated NCX file is broken if title of the book contains `&`.

**Comment by dougmassay** [comment]
Hard to believe something like that has never been encountered before. Are you sure that's the underlying reason for the failure?

Epub2 or Epub3

**Comment by johnfactotum** [comment]
Yes, the NCX file works after manually changing `&` to `&amp;`. Otherwise the book still works fine. Just that the table of contents will be empty.

I discovered this while looking at the EPUB file in https://github.com/johnfactotum/foliate/issues/819. The file looks like it was generated by a version of KindleUnpack (it has a `BEGIN INFORMATION ONLY` section which contains metas with the exact same names as those in KindleUnpack, as well as an unreachable coverpage with the `inserted` idref). The NCX file in it has an `&` in the `text` in `docTitle`.

So I went on a found a MOBI file with `&` in the title, unpacked it with KindleUnpack, and it has the same problem. The `&` in the title is not escaped.

**Comment by dougmassay** [comment]
Any KF8 Kindlebook that has an unescaped ampersand in the title metadata is broken. Broken Kindlebook can break kindleunpack. We try to  make sure that broken mobis don't _crash_ KindleUnpack, but it's pretty hard for us to accommodate every possible scenario that a bad Kindlebook might present to KindleUnpack. None of the standard Kindlebook creation tools that I know of would create title metadata with an unescaped ampersand.

We'll look into it further, but I don't like to travel too far down the rabbit-hole of trying to accommodate "wildcat" Kindlebooks.

**Comment by johnfactotum** [comment]
Just checked. In this particular book, the updated title (503) in EXTH doesn't contain an ampersand. However, it does have one in the title in MOBI header (the one you get from 0x54 and 0x58). And the latter title is the one used by KindleUnpack.

Also, the ampersand is escaped in the OPF. Just not in the NCX.

**Comment by kevinhendricks** [comment]
Yes, we use the exact same Metadata 'Title' value in the opf and ncx generation routines but in the opf we run escapeit(unescapeit(val)) to first undo any xml escaping and then xmlescape it.

We do not do that for the ncx generation code.
I will look into making things more robust for ncx generation.

**Comment by kevinhendricks** [comment]
Just pushed this change to master.  Please confirm this fixes your issue so I can then close this.

Thank you for  your bug report.

**Comment by johnfactotum** [comment]
It does fix the issue. Thanks!
