### ISSUE TITLE
Split xhtml per page based on apnx

### ISSUE THREAD

**Issue by GeorgeSuperBlue** [kevinhendricks/KindleUnpack#45]
Could you please add an option to split the xhtml file inside epub per page based on apnx when apnx is selected?
Thanks in advance

**Comment by dougmassay** [comment]
I agree. This kind of post-processing is not in KindleUnpack's wheelhouse. I also don't see a lot of users utilizing a one file per page strategy. What would be the point?

**Comment by GeorgeSuperBlue** [comment]
Thank you for your quick reply.
I selected apnx and ran kindleunpack, but no matter which viewer I use to load the created epub, it won't be based on the number of pages listed in "page-map.xml".
Also, even if you read page-map.xml, it does not clearly indicate from where to where one page is.

This is the reason.

>"Also post processing the resulting epub in Caliber or Sigil with find and replace is easily doable by finding the page ids and inserting split markers."

Does the page ID mean <p class="calibre">?
I don't think <p class="calibre"> is based on apnx.

**Comment by kevinhendricks** [comment]
Huh?  An "id" is an element attribute and marks a potential destination for a url link.
It has nothing to do with "class" attributes.

KindleUnpack will parse a valid apnx and create either an epub3 nav pagelist or an epub2 adobe pagemap.

Not all readers support epub3 pagelists set in the nav.  And only Adobe based readers support adobe pagemaps in epub2.

**Comment by kevinhendricks** [comment]
AFAICT, there is no code in KindleUnpack to create a Nav PageList for epub3.  That said, that can be done in Sigil and Calibre based on the generated adobe page-map.xml

**Comment by GeorgeSuperBlue** [comment]
> Only Adobe based readers support adobe pagemaps in epub2.

Sorry, I should have mentioned this first.


"ade viewer" does not display correctly either.

The total page count is based on apnx, but the current page count is not displayed correctly unless the xhtml is split (maybe).

Example

page0004.xhtml is dealing with page 9,

AND page0005.xhtml handles pages 10 through 100.

When viewed with ADE, the current page number goes from 9 to 100!

**Comment by dougmassay** [comment]
Why do you believe epub renderers are going to show "correct" page counts just because the epub is split into one page files based on the apnx?

**Comment by kevinhendricks** [comment]
If your pagemap.xml file is correct, then the bug is in your reader.  Please zip up and post both your apnx file and the resulting pagemap.xml file.

**Comment by GeorgeSuperBlue** [comment]
https://ufile.io/t6n1psyy
If you do not like the uploader, please specify
I sincerely appreciate you making time for my geeky questions.

**Comment by kevinhendricks** [comment]
That site tried to download malware.   I was finally able to get the file and your pagemap xml is very broken.  It has no ids found.  Almost all links point to the same file. Which means either your apnx is broken or that apnx does not belong or match the book you are unpacking.

This is not related to KindleUnpack at all.  If you give KindleUnpack crap input it will create crap output.

**Comment by GeorgeSuperBlue** [comment]
sincerely apologize.
Thank you for your help so far.
I give up on problem solving.

**Comment by GeorgeSuperBlue** [comment]
PS
The combination of page-map.xml and apnx is correct.
In other words, there seems to be a problem with the original azw.
This is a problem unrelated to kindleunpack.
I sincerely apologize again for bringing you into such trouble.
