### ISSUE TITLE
AttributeError: ‘str‘ object has no attribute ‘decode‘

### ISSUE THREAD

**Issue by zoujuny** [kevinhendricks/KindleUnpack#49]
Conversion Log 

Input Path = "/Volumes/Ventoy/ebook/程序员必读之软件架构.azw3"
Output Path = "/Users/****/ebook/my-epub"
Epub Output Type Set To: ePub 3

Please Wait ...

Palm DB type: BOOKMOBI, 253 sections.
Unpacking a KF8 book...
Processing K8 section of book...
Mobi Version: 8
Codec: utf-8
Title: 程序员必读之软件架构
EXTH Title: 程序员必读之软件架构
No compression
Unpacking images, resources, fonts, etc
Extracting image: cover00202.jpeg from section 202
Extracting image: thumb00203.jpeg from section 203
Extracting image: image00204.jpeg from section 204
Extracting image: image00205.jpeg from section 205
Extracting image: image00206.jpeg from section 206
Extracting image: image00207.jpeg from section 207
Extracting image: image00208.jpeg from section 208
Extracting image: image00209.jpeg from section 209
Extracting image: image00210.jpeg from section 210
Extracting image: image00211.jpeg from section 211
Extracting image: image00212.jpeg from section 212
Extracting image: image00213.jpeg from section 213
Extracting image: image00214.jpeg from section 214
Extracting image: image00215.jpeg from section 215
Extracting image: image00216.jpeg from section 216
Extracting image: image00217.jpeg from section 217
Extracting image: image00218.jpeg from section 218
Extracting image: image00219.jpeg from section 219
Extracting image: image00220.jpeg from section 220
Extracting image: image00221.jpeg from section 221
Extracting image: image00222.jpeg from section 222
Extracting image: image00223.jpeg from section 223
Extracting image: image00224.jpeg from section 224
Extracting image: image00225.jpeg from section 225
Extracting image: image00226.jpeg from section 226
Extracting image: image00227.jpeg from section 227
Extracting image: image00228.jpeg from section 228
Extracting image: image00229.jpeg from section 229
Extracting image: image00230.jpeg from section 230
Extracting image: image00231.jpeg from section 231
Extracting image: image00232.jpeg from section 232
Extracting image: image00233.jpeg from section 233
Extracting image: image00234.jpeg from section 234
Extracting image: image00235.jpeg from section 235
Extracting image: image00236.jpeg from section 236
Extracting image: image00237.jpeg from section 237
Extracting image: image00238.jpeg from section 238
Extracting image: image00239.jpeg from section 239
Extracting image: image00240.jpeg from section 240
Extracting image: image00241.jpeg from section 241
Extracting image: image00242.jpeg from section 242
Extracting image: image00243.jpeg from section 243
Extracting image: image00244.jpeg from section 244
Extracting image: image00245.jpeg from section 245
Extracting image: image00246.jpeg from section 246
Extracting image: image00247.jpeg from section 247
Extracting image: image00248.jpeg from section 248
Unpacking raw markup language
Processing ncx / toc
Error: 'str' object has no attribute 'decode'
Traceback (most recent call last):
  File "/Users/zouwj/MyProjects/github/KindleUnpack/KindleUnpack.pyw", line 370, in unpackEbook
    kindleunpack.unpackBook(infile, outdir, apnxfile, epubversion, use_hd, dodump=dump, dowriteraw=writeraw, dosplitcombos=splitcombos)
  File "/Users/zouwj/MyProjects/github/KindleUnpack/lib/kindleunpack.py", line 947, in unpackBook
    process_all_mobi_headers(files, apnxfile, sect, mhlst, K8Boundary, False, epubver, use_hd)
  File "/Users/zouwj/MyProjects/github/KindleUnpack/lib/kindleunpack.py", line 864, in process_all_mobi_headers
    processMobi8(mh, metadata, sect, files, rscnames, pagemapproc, k8resc, obfuscate_data, apnxfile, epubver)
  File "/Users/zouwj/MyProjects/github/KindleUnpack/lib/kindleunpack.py", line 531, in processMobi8
    ncx_data = ncx.parseNCX()
  File "/Users/zouwj/MyProjects/github/KindleUnpack/lib/mobi_ncx.py", line 80, in parseNCX
    toctext = toctext.decode(self.mh.codec)
AttributeError: 'str' object has no attribute 'decode'

Error: Unpacking Failed

**Comment by kevinhendricks** [comment]
Fixed via your pr.  Thank you.
