### ISSUE TITLE
gui interface not start.

### ISSUE THREAD

**Issue by nibazshab** [kevinhendricks/KindleUnpack#50]
My python version is Python 3.11.5
KindleUnpack version is [7fe6f80](https://github.com/kevinhendricks/KindleUnpack/commit/7fe6f80fa9ed6cf79fed6e31bce0072a3481804a), clone this repo just now.

I try double-click the KindleUnpack.pyw, but anything not happened。

Then I try use command `pythonw .\KindleUnpack.pyw`, also have nothing happened. I got nothing log or tip.

If just use `python kindleunpack.py` to use command-line interface, it can be work well.

**Comment by dougmassay** [comment]
Sounds like you may have accidentally associated .pyw files with something other than Python. If Python isn't on your PATH, Windows ask you what app you'd like to use to open .pyw files the first time. I chose the Python Launcher.

It works fine on my Windows 10 machine with Python 3.11.9 by double-clicking on KindleUnpack.pyw. I downloaded the latest commit's source to match what you're using.

**Comment by kevinhendricks** [comment]
Maybe your python version is lacking the necessay Tk widget support?  The Mobiunpack gui uses Tk.

**Comment by dougmassay** [comment]
There's a thought. If you didn't use a full installer such as the one from Python.org (or if you customized the installation), Tk may not have been installed.

**Comment by nibazshab** [comment]
Oh thanks, My python is install by custom. Now it's work well
