### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by JasonGilley** [kevinhendricks/KindleUnpack#8]
I am using v0.80 in Calibre and it appears that KU cannot handle large files. I have a 196mb azw4 and I get the following error:

![image](https://cloud.githubusercontent.com/assets/11808311/6997699/e6020330-db8b-11e4-9502-9ed4b4711456.png)

**Comment by kevinhendricks** [comment]
Hi,
Are you using a 32 bit machine?  How much memory do you have installed?  Python is simply not the most memory efficient when it comes to building up large strings from sequences of smaller strings.   I recommend trying again on a 64 bit machine with a reasonable amount of memory.

KevinH

**Comment by JasonGilley** [comment]
I am using 64 bit Windows 7 with 16GB Ram.

Date: Sun, 5 Apr 2015 10:49:08 -0700

**Comment by kevinhendricks** [comment]
Hi,

Are you using a 32 bit version of python or 64 bit version?

**Comment by JasonGilley** [comment]
I am using the Calibre plugin 0.80. I did not have to install Python.

Date: Sun, 5 Apr 2015 13:32:09 -0700

**Comment by kevinhendricks** [comment]
Hi,

Sorry but calibre itself takes up a big chunk of memory, especially when converting or unpacking.

Your best bet is to install Python for Windows 64 bit and try running KindleUnpack directly from the gui.  I strongly recommend the free community version from ActiveState called ActivePython as it includes most of the libraries you will want.  KindleUnpack v0.80 will work with either Python 3.4 or Python 2.7 (your choice).

Kevin

**Comment by JasonGilley** [comment]
Awesome. The standalone worked. I would note the limitations for the plugin to other users if I knew a good place to write it.
Thanks again.

Date: Sun, 5 Apr 2015 13:45:59 -0700

**Comment by kevinhendricks** [comment]
Closing as it has more to do with Calibre's memory use and not the standalone version.
